apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: capacitor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: capacitor
  template:
    metadata:
      labels:
        app: capacitor
    spec:
      serviceAccountName: capacitor
      containers:
        - name: capacitor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: AUTH
              value: "noauth"
            - name: IMPERSONATE_SA_RULES
              value: "noauth=monitoring:capacitor"

