apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: capacitor-helm-chart
  namespace: flux-system

spec:
  interval: 1m
  url: https://github.com/navbilakajamaideen-netcoreunbxd/capacitor-helm-chart
  ref:
    branch: main
