replicaCount: 1

image:
  repository: ghcr.io/gimlet-io/capacitor
  tag: v0.4.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: true
  host: flux-ui.yourdomain.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
