apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: opencost
spec:
  interval: 15m
  chart:
    spec:
      chart: opencost
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: flux-system
      version: '1.108.*'
  values:
    opencost:
      ui:
        baseUrl: /
      prometheus:
        internal:
          enabled: true
          namespaceName: monitoring
          serviceName: prometheus-kube-prometheus-prometheus
          port: 9090
      exporter:
        env:
          RESOLUTION_1H_RETENTION: "168"
          RESOLUTION_1D_RETENTION: "30"
