apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml # keep ONLY if this file exists

configMapGenerator:
  - name: capacitor-cluster-values
    files:
      - values.yaml=../../service/capacitor/capacitor.yaml

generatorOptions:
  disableNameSuffixHash: true
