replicaCount: 1

image:
  registry: ghcr.io
  repository: headlamp-k8s/headlamp
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: true
  automount: true
  name: headlamp

rbac:
  create: true

config:
  baseURL: ""
  watchPlugins: false

pluginsManager:
  enabled: false

securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 100
  fsGroup: 101

podSecurityContext:
  fsGroup: 101
