apiVersion: v1
kind: ConfigMap
metadata:
  name: capacitor-cluster-values
  namespace: flux-system
data:
  values.yaml: |
    clusterName: minikube
    ingress:
      enabled: false
    service:
      type: ClusterIP
      port: 9000
